metadata:
  name: django-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
      version: green
  template:
    metadata:
      labels:
        app: django
        version: green
    spec:
      containers:
      - name: django-container
        image: your-django-image:latest  # Replace with your actual image
        ports:
        - containerPort: 8000