pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Clone Repository') {
            steps {
                
                sh 'git branch'  
            }
        }

        stage('Set Up Python Environment') {
            steps {
                
                sh 'python3 -m venv $VENV_DIR'

                
                sh './$VENV_DIR/bin/pip3 install --upgrade pip'
                sh './$VENV_DIR/bin/pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                
                sh './$VENV_DIR/bin/pytest messaging_app/tests --junitxml=report.xml'
            }
        }

        stage('Publish Report') {
            steps {
                
                junit 'report.xml'
            }
        }
    }
}