#!/bin/bash

echo "Deploying Blue version..."
kubectl apply -f blue_deployment.yaml

echo "Deploying Green version..."
kubectl apply -f green_deployment.yaml

echo "Applying service..."
kubectl apply -f kubeservice.yaml

echo "Checking logs for Green version:"
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD
