#!/bin/bash

echo "Applying Rolling Update to Blue Deployment..."
kubectl apply -f blue_deployment.yaml

echo "Monitoring rollout status..."
kubectl rollout status deployment/django-blue

echo "Testing for downtime using curl..."


for i in {1..10}
do
  curl -s http://localhost:8000/ || echo "Request failed"
  sleep 1
done

echo "Verifying the updated pods..."
kubectl get pods -l version=blue